# Generated by Django 5.0.6 on 2024-06-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the album name', max_length=200)),
                ('release_date', models.DateField()),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('album_cover', models.ImageField(upload_to='')),
                ('genre', models.ManyToManyField(blank=True, help_text='Select a genre for this album', to='rating.genre')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rating.artist')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the song name', max_length=200)),
                ('duration', models.DurationField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rating.album')),
            ],
        ),
    ]
