# Generated by Django 5.0.6 on 2024-07-17 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_usersongrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersongrating',
            name='song',
        ),
        migrations.AddField(
            model_name='usersongrating',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='rating.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersongrating',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='usersongrating',
            constraint=models.UniqueConstraint(fields=('user', 'album'), name='unique_composite_key'),
        ),
    ]
