# Generated by Django 5.0.6 on 2024-07-17 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_remove_usersongrating_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSongRating',
            new_name='UserAlbumRating',
        ),
    ]
