# Generated by Django 5.0.6 on 2024-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_rename_usersongrating_useralbumrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
