# Generated by Django 5.0.6 on 2024-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_alter_album_rating_alter_useralbumrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbumrating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
