# Generated by Django 5.0.6 on 2024-07-22 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_alter_album_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAlbumRating',
            new_name='UserAlbumRatings',
        ),
    ]
