# Generated by Django 5.0.6 on 2024-07-22 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0013_rename_useralbumrating_useralbumratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAlbumRatings',
            new_name='Ratings',
        ),
    ]
